export interface AgentTrigger {
  minuteMark: number;
  message: string;
}

export const LESSON_TRIGGERS: Record<number, AgentTrigger[]> = {
  1: [
    { minuteMark: 2, message: "O Daniel acabou de falar que o método tem 4 grandes etapas: Matéria-Prima, Ativação, Escala e Controle. Me conta: qual dessas etapas você sente que é mais fraca na sua operação hoje? Vamos prestar atenção especial nela ao longo do curso." },
    { minuteMark: 5, message: "Ele mencionou que a Redrive cresceu 3.000% em um único ano — de 40 para mais de 1.300 clientes. O segredo? Aplicar o próprio método. E você, quantos clientes tem hoje na sua carteira? Anota esse número — vamos acompanhar sua evolução." },
    { minuteMark: 9, message: "Ponto importante: 99% dos celulares brasileiros têm WhatsApp e 50% dos consumidores já compram por mídias sociais ou ferramentas de conversa. Você já usa o WhatsApp como ferramenta profissional de vendas ou ainda trata ele de forma casual?" },
    { minuteMark: 13, message: "O Daniel fechou com um dado poderoso: a taxa de conversão no chat commerce é de 10 a 20%, contra 1 a 2% no e-commerce tradicional. E 71% das pessoas compram por comodidade, não por preço. Cria um tópico 'Dados-Chave' nas notas e registra esses números — eles vão guiar suas decisões." },
  ],
  2: [
    { minuteMark: 2, message: "O Daniel explicou a curva de envolvimento do cliente. Se você perde 8% dos clientes por mês, em um ano você perde 100% da carteira. Você sabe qual é a sua taxa de cancelamento mensal? Anota isso — é o primeiro número que você precisa conhecer." },
    { minuteMark: 7, message: "Ele mostrou os 3 cenários: A (início, só entrada), B (estagnação, entrada e saída se equilibram) e C (crescimento previsível). Em qual cenário você acha que seu negócio está agora? Isso define qual é a prioridade da sua operação." },
    { minuteMark: 12, message: "Olha esse dado: fazendo 40 vendas/mês com 10% de churn, em 11 meses você já estagna. A máquina de vendas não é opcional — é vital. Cria um tópico 'Máquina de Vendas' nas notas e anota: quantas vendas novas você precisa fazer por mês só pra manter o tamanho atual do negócio?" },
    { minuteMark: 18, message: "O Daniel falou sobre Inbound vs Outbound e o funil em Y. Ele mesmo usou só Outbound nos primeiros 3 anos da Redrive e fez 18.000+ vendas. Qual estratégia faz mais sentido pro seu momento? Pro negócio pequeno, ele recomenda Outbound — menos custo, resultado mais direto." },
    { minuteMark: 24, message: "Conceito fundamental: toda venda nasce de um relacionamento, e todo relacionamento nasce de uma conversa. O processo de vendas tem 3 etapas: Prospecção → Qualificação → Venda. É igual na loja de roupas e é igual no WhatsApp. Anota essa sequência — ela não muda." },
  ],
  3: [
    { minuteMark: 1, message: "Janela de Atenção — um dos conceitos mais importantes do curso. Você sabia que recebemos em um dia a mesma quantidade de informação que nossos avós receberam na vida inteira? São 6.000 marcas impactando nosso cérebro por dia. Por isso a atenção do cliente é tão disputada." },
    { minuteMark: 4, message: "Dado crucial: se você atende o cliente no mesmo minuto que ele chamou, a taxa de conversão melhora até 400%. Com 3 minutos de espera, cai pra 98%. E a janela real? São apenas 7 minutos. Depois disso, retomar a atenção fica muito mais difícil. Quanto tempo sua equipe demora pra responder hoje?" },
    { minuteMark: 7, message: "53% das pessoas compram de quem respondeu primeiro. Não necessariamente de quem tem o melhor produto — de quem respondeu antes. Cria um tópico 'Janela de Atenção' nas notas e anota: 7 minutos é o limite, resposta imediata = 400% mais conversão. Isso muda tudo." },
    { minuteMark: 9, message: "Os 3 pilares da atenção: Canal (onde você fala), Momento (quando o cliente está receptivo) e Mensagem (o que você diz). O WhatsApp é o canal mais forte porque o brasileiro passa 2h/dia nele e abre pelo menos 4 vezes por hora. Como você pode reduzir seu tempo de resposta usando Redrive?" },
  ],
  4: [
    { minuteMark: 2, message: "Primeira descoberta: volume de mensagem impacta diretamente nas vendas. Quando a Redrive aumentava o volume de disparos, as vendas subiam. Quando diminuía, caíam. Simples assim. Quantas mensagens de prospecção sua operação manda por dia?" },
    { minuteMark: 5, message: "Descoberta surpreendente: as mensagens de WhatsApp não geram só vendas diretas — elas aumentam o tráfego orgânico do site, visitas à loja física e seguidores nas redes sociais. O cliente não respondeu? Pode ser que ele vá te procurar no Google depois. O WhatsApp gera impacto muito além da conversa direta." },
    { minuteMark: 8, message: "Ponto de ouro: dose a quantidade de mensagens pelo atendimento! 20% das pessoas respondem rápido, e você tem 7 minutos. Não adianta mandar 1.000 mensagens se não consegue atender quem responde. Mande conforme sua capacidade de atendimento. Qual é o seu limite hoje?" },
    { minuteMark: 11, message: "Mídias que funcionam no WhatsApp: TEXTO e ÁUDIO. Imagem e vídeo diminuem a taxa de conversão! O áudio ideal é como se você estivesse falando com um amigo — 20-30 segundos, natural, direto. Nada de áudio de radialista." },
    { minuteMark: 14, message: "DDD igual = mais conversão. Perfil de mulher engaja mais. Foto pessoal profissional funciona melhor que logomarca. E apresentação cortês gera quase 100% de taxa de resposta. Cria um tópico 'Checklist de Perfil' nas notas: DDD local, foto profissional, apresentação cortês." },
    { minuteMark: 19, message: "Horário de disparo importa: entre 15h e 16h é o horário nobre do empreendedor. Mas depende do seu público — pizza faz sentido no final da tarde, não de manhã. E a segmentação é o segredo: quanto mais personalizada a mensagem, maior a taxa de resposta. Anota o melhor horário pro seu público." },
    { minuteMark: 23, message: "Segmentação em dois níveis: 1) escolher COM QUEM falar (baseado em interesse) e 2) construir uma MENSAGEM que dialogue com aquela pessoa. O exemplo da médica cardiologista mostra isso perfeitamente — 'Doutora Mariana, estou fazendo um trabalho com médicas cardiologistas'. Quanto mais personalizado, mais resultado." },
  ],
  5: [
    { minuteMark: 2, message: "Matéria-prima = leads = contatos. Sem isso, não existe operação. O Daniel mostrou a pirâmide de Chet Holmes: só 3% estão prontos pra comprar agora, mas com prospecção ativa você fala com 100% — incluindo os 90% que nem estavam pensando no seu produto." },
    { minuteMark: 5, message: "O melhor público pra prospectar no WhatsApp são pessoas na fase de 'interesse' e 'consideração' do funil. Elas dão mais atenção. Evite quem acabou de comprar do concorrente — a atenção deles está em outro lugar. Qual fase do funil você está mirando hoje?" },
    { minuteMark: 8, message: "Canais de captação na Redrive: WhatsApp (grupos segmentados — cliente já gerou 1 milhão de leads só de grupos!), Instagram (teste em blocos pequenos de 200-600), Cadastro Nacional de Empresas (melhor no interior), Google Maps (2% de conversão em vendas). Quantos desses canais você já usa?" },
    { minuteMark: 11, message: "Dica de ouro pro Instagram: pegue 200-600 contatos de UM perfil, valide se funciona, estresse aquele grupo todo antes de abrir outro. Não saia pegando milhares de uma vez. E se não funcionar, troque a comunicação antes de trocar o público." },
    { minuteMark: 14, message: "Tráfego pago + WhatsApp = combinação poderosa. A melhor estratégia: fazer campanhas que jogam o cliente direto pro WhatsApp, onde você atende imediatamente (lembra da janela de 7 minutos!). Cria um tópico 'Fontes de Matéria-Prima' nas notas e liste todos os canais que pode usar." },
  ],
  6: [
    { minuteMark: 2, message: "Estilo Toninho (panfleto, só vende) vs Estilo Ritinha (relacionamento primeiro). 11% bloqueiam mensagens com cara de oferta + 28% ignoram = 40% de perda! A venda nasce do relacionamento, não da oferta direta. Como é a sua abordagem atual?" },
    { minuteMark: 5, message: "O ato mais importante do processo é a PROSPECÇÃO, não a venda. Na prospecção eu ainda não quero vender — quero gerar relacionamento. É como o vendedor da loja que primeiro pergunta 'como posso ajudar?' antes de mostrar as calças. Você separa prospecção de venda na sua operação?" },
    { minuteMark: 8, message: "Inbound vs Outbound mudam completamente a abordagem. No Inbound, o cliente já sabe que tem uma dor — valide se você pode atendê-lo. No Outbound, o cliente nem te conhece — valide se ele tem a dor que você resolve. São comunicações diferentes!" },
    { minuteMark: 13, message: "Os 4 passos da mensagem perfeita: 1️⃣ Ser cortês ('Oi João, tudo bem?') 2️⃣ Explicar como conseguiu o contato (a ponte) 3️⃣ Mostrar como gera valor 4️⃣ Call to action (pergunta de qualificação). Essa estrutura gera taxas de resposta de 80-90%. Anota isso!" },
    { minuteMark: 18, message: "O que NÃO fazer: mensagem com emoji demais, link na primeira mensagem (tira o cliente do WhatsApp!), preço, gatilho mental forçado, mensagem longa, encerrar com 'atenciosamente' (fecha a porta da conversa). A mensagem tem que parecer NATURAL — como se falasse com um amigo." },
    { minuteMark: 25, message: "Exemplo real com 80% de taxa de resposta: 'Oi Maria, chegou uma calça jeans linda aqui na loja. Você quer que eu te mande as fotos?' Gatilho de curiosidade! Depois: 'Qual dessas você gostou mais?' → 'Quer vir na loja ou mando na sua casa pra provar?' Funil completo pelo WhatsApp!" },
    { minuteMark: 35, message: "Estratégia de PESQUISA para vendas complexas (inglês, terapia, oratória): 3 perguntas — 1) Quais dessas dores você tem? 2) Já pesquisou alguma solução? 3) Se eu tiver algo que resolve, quer conhecer? O cliente ME DIZ que quer — inverte o processo de prospecção!" },
    { minuteMark: 45, message: "Regra de ouro: NO WHATSAPP, UM FUNIL POR VEZ. Não tente vender dois produtos na mesma mensagem — você não vende nenhum. Seguro de carro pros homens, seguro de vida pras mulheres. Segmentação + comunicação específica = resultado." },
    { minuteMark: 55, message: "Estratégia de timing mensal: começo do mês = prospectar muito (plantar), meio do mês = qualificar quem demonstrou interesse, final do mês = follow-up e fechamento com quem ficou em cima do muro. A máquina de prospecção nunca pode parar!" },
    { minuteMark: 62, message: "Mesmo a resposta negativa é qualificação! O cliente que diz 'não agora' pode virar venda futura. Peça: 'Se eu tiver uma oportunidade especial, posso te mandar por aqui?' Mantenha o relacionamento. Cria um tópico 'Modelo de Mensagem' nas notas e monte sua mensagem seguindo os 4 passos." },
  ],
  7: [
    { minuteMark: 2, message: "Escala = fazer mais com menos. 70% dos consumidores esperam resposta imediata. Com 100+ clientes chamando ao mesmo tempo, é impossível sem ferramenta. É por isso que automação não é luxo — é necessidade. Qual é o seu gargalo de atendimento hoje?" },
    { minuteMark: 5, message: "Dado impactante: vendedores passam só 37% do tempo efetivamente falando com clientes. O resto é tarefa repetitiva, pesquisa, atualização de CRM. A automação libera o vendedor pra fazer o que importa: VENDER. Quanto tempo sua equipe gasta em tarefas que não são vender?" },
    { minuteMark: 8, message: "Agentes de IA: 95% das implementações de IA falham! Por quê? Porque tentam automatizar processos que nem sabem se funcionam. A regra é: primeiro valide o processo manualmente, depois replique com IA. Nunca escale algo que você não sabe como funciona." },
    { minuteMark: 12, message: "Jornadas automatizadas: onboarding, cobrança (63% de taxa de resposta!), pós-venda, reativação, pesquisa de satisfação. Cada contato do ciclo de vida do cliente pode ser uma jornada automática. Quais jornadas você já tem automatizadas no seu negócio?" },
    { minuteMark: 17, message: "O Maestro como copiloto: não substitui o vendedor, MELHORA a resposta dele. Exemplo real — cliente disse 'não tenho tempo', o Maestro sugeriu: 'Se eu te apresentar como ganhar mais clientes em menos tempo, faria sentido?' Resultado: a conversa continuou e virou venda!" },
    { minuteMark: 22, message: "Reversão de cancelamento com IA: cliente queria cancelar porque ia criar seu próprio produto. O Maestro sugeriu: 'Você pode usar a ferramenta pra prospectar afiliados e lançar seu produto, já pensou nisso?' Virou a chave! Cria um tópico 'Automações Prioritárias' nas notas." },
    { minuteMark: 27, message: "Escalar = mais clientes SEM aumentar custo na mesma proporção. Se 1.000 clientes custam X, 2.000 não podem custar 2X — senão não vale. IA e automação são a chave pra quebrar essa proporção. Qual processo você automatizaria primeiro?" },
  ],
  8: [
    { minuteMark: 2, message: "Controle começa com CRM. Antes da Redrive, o Daniel controlava em planilha e no 3º disparo já duplicava contatos. CRM é o perfil do cliente dentro do seu negócio — quanto mais informação, mais vendas. Você usa CRM hoje? Como organiza seus contatos?" },
    { minuteMark: 5, message: "Dois pilares do crescimento: VENDER mais e RETER mais. Mas mesmo ex-clientes são importantes — mantenha o relacionamento para jornadas de reativação. E a urgência de contatos? Quantos dos seus 4-5 mil contatos no WhatsApp fazem 2-3 anos que você não fala? Networking parado é dinheiro parado." },
    { minuteMark: 8, message: "Metodologia de vendas + CRM = poder. A Redrive captura informações da conversa e distribui nas metodologias automaticamente — autoridade, investimento, dor, urgência. Isso gera um índice de probabilidade de fechamento. Você usa alguma metodologia de vendas hoje?" },
    { minuteMark: 11, message: "Gestão de atendimento: com 2-3 WhatsApps na empresa, você tem uma caixa preta. Vendedor que sai leva parte do faturamento junto. O atendimento TEM que estar sob seu controle, vinculado ao CRM. NPS, tempo de espera, satisfação — tudo precisa ser medido." },
    { minuteMark: 14, message: "Funil de oportunidade + predição de vendas: organize contatos por probabilidade de fechamento, priorize quem está mais perto de fechar no final do mês, prospecte muito no início. Se tem poucas oportunidades → precisa qualificar mais → precisa prospectar mais → precisa melhorar a comunicação. Cada parafuso importa." },
    { minuteMark: 17, message: "Os primeiros clientes da Redrive (desde 2020) fazem 70% das vendas usando a ferramenta. A própria Redrive faz 73% das vendas com esse método. Funciona em 30 países. Não é mágica — é processo, gestão e método aplicado com qualidade." },
    { minuteMark: 19, message: "Parabéns por completar o curso! 🎉 Agora é hora de agir: volta no dashboard, revisa suas notas de todas as aulas, e vamos montar seu plano de ação. Livros recomendados pelo Daniel: 'A Magia da Conversa' (manual prático) e 'Chat First' (negócios na era da IA). Estou aqui pra te ajudar a implementar tudo!" },
  ],
};
